### ISSUE TITLE
How do I add my own dataset?

### ISSUE THREAD

**Issue by LeeSure5986** [cwida/ALP#26] opened 2024-12-01 12:55 UTC
I want to test the ALP algorithm with my own dataSet, but I found that the double_columns.hpp file requires some additional parameters when adding dataSets. Such as factor, exponent, exceptions_count, bit_width, and suitable_for_cutting. Do these parameters need to be added manually, or can the algorithm get them automatically?

**Comment by azimafroozeh** [comment] 2024-12-01 22:02
Hi,

ALP determines these parameters (such as `factor`, `exponent`, `exceptions_count`, `bit_width`, and `suitable_for_cutting`) automatically. These are primarily intended for low-level debugging and not something you need to set manually.

To make testing ALP on your dataset simpler and abstract away internal details, we’ve rewritten the benchmarking framework. Please check out the relevant [PR](https://github.com/cwida/ALP/pull/28) and our [Guide](https://github.com/cwida/ALP/blob/main/how_to_benchmark_your_dataset.md) for step-by-step instructions.

Feel free to share your dataset and results with us. Your feedback is valuable and will help us improve ALP further.

Let us know if you have any other questions!

**Comment by LeeSure5986** [comment] 2024-12-02 03:21
Thank you for your response. I still have the following question: How does the ALP algorithm handle missing values in the dataset? When I tested a dataset with missing values, it reported an error and could not execute properly.

**Comment by azimafroozeh** [comment] 2024-12-04 12:20
I have added the compression and decompression speed benchmarks to the `bench_your_own'. Please try [this PR](https://github.com/cwida/ALP/pull/31).

Regarding your first question, could you clarify what you mean by "missing values"?

**Comment by LeeSure5986** [comment] 2024-12-06 01:08
Thank you very much for your reply.
"Null" in floating-point data represents missing values, which are used to indicate data loss or unknown values. For example, in the floating-point data series: 3.1, Null, 3.2, 3.6, Null, 3.8, the second and fifth positions are missing values, representing data loss.

May I ask if the experimental results of the ALP algorithm are the only ones that can be obtained using my dataset? Is it not possible to test other comparison algorithms on my dataset?

**Comment by azimafroozeh** [comment] 2024-12-06 01:32
Supporting `NULL` values is out of scope for this repository, as it focuses solely on the ALP algorithm, a compression scheme for floating-point numbers (`doubles`). Handling `NULL` values would be managed by file formats that integrate ALP, such as the upcoming **FastLanes File Format**, which will include `NULL` support. You can follow its progress here: [FastLanes GitHub Repository](https://github.com/cwida/FastLanes)

To test the compression ratio or compression/decompression speed of ALP on your dataset, replace `NULL` values with `-inf` and run the ALP benchmarks.

For testing other algorithms on your dataset, refer to the [Availability and Reproducibility Initiative Report](https://github.com/cwida/ALP/blob/main/availability_reproducibility_initiative_report.md), which explains how benchmarks for our publications were conducted. To test using your dataset:

1. Replace the ALP dataset in this file:  [alp_dataset.hpp](https://github.com/cwida/ALP/blob/main/data/include/double/alp_dataset.hpp) with your dataset.

2. Run the benchmarking script:  [master_script.sh](https://github.com/cwida/ALP/blob/main/publication/script/master_script.sh)

This process allows you to evaluate the ALP algorithm and compare it with other algorithms using your dataset.

**Comment by LeeSure5986** [comment] 2024-12-06 05:42
How should the dataset parameters be set in the file alp_dataset.hpp, such as factor, exponent, exceptions_count, bit_width, and suitable_for_cutting?

**Comment by azimafroozeh** [comment] 2024-12-06 10:49
ALP determines parameters like `factor`, `exponent`, `exceptions_count`, `bit_width`, and `suitable_for_cutting` automatically. These are mainly intended for low-level debugging purposes and don't require manual adjustments. Since you're using the publication part of the repository for other compression schemes, these parameters are not critical for your application. You can assign arbitrary values to them.

**Comment by azimafroozeh** [comment] 2024-12-06 10:54
Additionally, keep in mind that the implementation of other schemes in this repository reflects the state of the code at the time we published the paper. It’s worth checking their codebases to see if there have been improvements or bug fixes since then.

**Closed** 2024-12-15 17:47 UTC
